"""agent_episodes hypertable + episode_corrections (Week 1 / B3)

Revision ID: 002
Revises: 001
Create Date: 2026-04-19 00:00:00.000000

Schema source: trading-floor-plan/schemas/postgres-episodes.sql

Spec compliance notes:
- agent_episodes is a Timescale hypertable partitioned on ts (1d chunk).
- Immutability is enforced by triggers, not by application discipline.
  UPDATE / DELETE are rejected for every role except `migration_admin`.
- Corrections go to episode_corrections (separate table) — never update in place.
- agent_version format is enforced by CHECK constraint.
- cycle_id is generated by the application in UUIDv7 (uuid6 package); the DDL
  does not assume the pg_uuid_v7 extension.
- Compression policy: chunks >30d are compressed.
- Retention drop is intentionally NOT enabled (waits for Week 9 rollups).
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "002"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Timescale is required by 001; uuid-ossp gives us uuid_generate_v4()
    # for episode_corrections.correction_id default.
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    # Composite PK (episode_id, ts) is required by Timescale: any unique index
    # on a hypertable must include the partitioning column. episode_id is a
    # UUIDv7 (globally unique, time-ordered) so (episode_id, ts) is in
    # practice unique-on-episode_id too — the consumer's ON CONFLICT clause
    # uses (episode_id, ts) to deduplicate redelivered messages.
    op.execute(
        """
        CREATE TABLE agent_episodes (
            episode_id          UUID NOT NULL,
            ts                  TIMESTAMPTZ NOT NULL,
            cycle_id            UUID NOT NULL,
            cycle_started_at    TIMESTAMPTZ NOT NULL,
            subsystem           TEXT NOT NULL DEFAULT 'legacy',
            symbol              TEXT NOT NULL,
            agent_id            TEXT NOT NULL,
            agent_version       TEXT NOT NULL,

            market_snapshot     JSONB NOT NULL,
            input_state         JSONB NOT NULL,

            prompt              TEXT,
            raw_response        TEXT,

            parsed_signal       JSONB,
            reasoning           TEXT,

            latency_ms          INTEGER NOT NULL,
            cost_usd            NUMERIC(10, 6) DEFAULT 0,
            error               TEXT,

            regime_fingerprint  TEXT NOT NULL,
            regime_tags         TEXT[] DEFAULT ARRAY[]::TEXT[],

            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

            PRIMARY KEY (episode_id, ts),
            CONSTRAINT agent_version_format CHECK (
                agent_version ~ '^[a-f0-9]{8}:[a-zA-Z0-9_.-]+:[a-f0-9]{8}$'
            ),
            CONSTRAINT cycle_id_not_null CHECK (cycle_id IS NOT NULL),
            CONSTRAINT latency_non_negative CHECK (latency_ms >= 0)
        );
        """
    )

    op.execute(
        "SELECT create_hypertable('agent_episodes', 'ts', "
        "chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE, "
        "migrate_data => TRUE);"
    )

    op.execute("CREATE INDEX idx_episodes_cycle ON agent_episodes (cycle_id, ts DESC);")
    op.execute("CREATE INDEX idx_episodes_agent_ts ON agent_episodes (agent_id, ts DESC);")
    op.execute("CREATE INDEX idx_episodes_symbol_ts ON agent_episodes (symbol, ts DESC);")
    op.execute(
        "CREATE INDEX idx_episodes_regime ON agent_episodes (regime_fingerprint, ts DESC);"
    )
    op.execute("CREATE INDEX idx_episodes_agent_version ON agent_episodes (agent_version);")
    op.execute(
        "CREATE INDEX idx_episodes_subsystem_ts ON agent_episodes (subsystem, ts DESC);"
    )
    op.execute(
        "CREATE INDEX idx_episodes_errors ON agent_episodes (ts DESC) "
        "WHERE error IS NOT NULL;"
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_episode_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            IF current_user = 'migration_admin' THEN
                RETURN COALESCE(NEW, OLD);
            END IF;
            RAISE EXCEPTION
                'agent_episodes is immutable. Use episode_corrections table for corrections. Operation: %, User: %',
                TG_OP, current_user;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    op.execute(
        """
        CREATE TRIGGER episodes_reject_update
            BEFORE UPDATE ON agent_episodes
            FOR EACH ROW
            EXECUTE FUNCTION reject_episode_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER episodes_reject_delete
            BEFORE DELETE ON agent_episodes
            FOR EACH ROW
            EXECUTE FUNCTION reject_episode_mutation();
        """
    )

    # No FK to agent_episodes: Timescale forbids a unique index on
    # episode_id alone (must include ts), and an FK against the composite
    # PK would require the corrections row to know the original ts. We
    # store episode_id as a value and validate join-side in queries.
    op.execute(
        """
        CREATE TABLE episode_corrections (
            correction_id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            episode_id          UUID NOT NULL,
            ts                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            corrected_by        TEXT NOT NULL,
            reason              TEXT NOT NULL,
            correction_payload  JSONB NOT NULL
        );
        """
    )
    op.execute("CREATE INDEX idx_corrections_episode ON episode_corrections (episode_id);")
    op.execute("CREATE INDEX idx_corrections_ts ON episode_corrections (ts DESC);")

    # Enable compression on chunks older than 30 days. segmentby (agent_id, symbol)
    # is the spec — both have low cardinality vs. row count, so compression is fat.
    op.execute(
        """
        ALTER TABLE agent_episodes SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'agent_id, symbol',
            timescaledb.compress_orderby = 'ts DESC'
        );
        """
    )
    op.execute("SELECT add_compression_policy('agent_episodes', INTERVAL '30 days');")

    op.execute(
        """
        CREATE VIEW latest_episode_per_cycle_agent AS
        SELECT DISTINCT ON (cycle_id, agent_id)
            episode_id, ts, cycle_id, symbol, agent_id, agent_version,
            parsed_signal, reasoning, latency_ms, error
        FROM agent_episodes
        ORDER BY cycle_id, agent_id, ts DESC;
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS latest_episode_per_cycle_agent;")
    op.execute("SELECT remove_compression_policy('agent_episodes', if_exists => TRUE);")
    op.execute("DROP TABLE IF EXISTS episode_corrections;")
    op.execute("DROP TRIGGER IF EXISTS episodes_reject_delete ON agent_episodes;")
    op.execute("DROP TRIGGER IF EXISTS episodes_reject_update ON agent_episodes;")
    op.execute("DROP FUNCTION IF EXISTS reject_episode_mutation();")
    op.execute("DROP TABLE IF EXISTS agent_episodes;")
